import type { FormWizardConfig } from '@/features/forms/core';

export const nativeTestFormConfig: FormWizardConfig = {
  steps: [
    {
      id: 'step-mdb',
      kind: 'single-choice',
      title: 'Êtes-vous déjà Marchand de Biens ?',
      variable: 'mdb_status',
      options: [
        { label: 'Oui', value: 'oui', next: 'step-transactions' },
        { label: 'Non', value: 'non', next: 'step-objective' },
      ],
    },
    {
      id: 'step-transactions',
      kind: 'single-choice',
      title: 'Combien de transactions avez-vous réalisées ?',
      variable: 'transactions',
      options: [
        { label: 'Aucune', value: 'aucune', next: 'step-objective' },
        { label: '1 à 2 opérations', value: '1_2', next: 'step-objective' },
        { label: 'Plus de 3 opérations', value: 'plus_3', next: 'step-situation' },
      ],
    },
    {
      id: 'step-objective',
      kind: 'single-choice',
      title: 'Quel est votre objectif principal aujourd’hui ?',
      variable: 'objective',
      options: [
        { label: 'Me former au métier de Marchand de Biens', value: 'formation', next: 'step-formation-reason' },
        { label: 'Accélérer mon activité actuelle', value: 'accelerer', next: 'step-situation' },
      ],
    },
    {
      id: 'step-situation',
      kind: 'single-choice',
      title: 'Quelle est votre situation actuelle ?',
      variable: 'situation',
      options: [
        { label: 'Salarié', value: 'salarie', next: 'step-delai' },
        { label: 'Indépendant', value: 'independant', next: 'step-delai' },
        { label: 'Sans activité', value: 'sans_activite', next: 'step-delai' },
      ],
    },
    {
      id: 'step-delai',
      kind: 'single-choice',
      title: 'Quand souhaitez-vous vous lancer ?',
      variable: 'delai',
      options: [
        { label: 'Immédiatement', value: 'immediat', next: 'step-capital' },
        { label: 'D’ici 3 mois', value: '3_mois', next: 'step-capital' },
        { label: 'Plus tard', value: 'plus_tard', next: 'step-capital' },
      ],
    },
    {
      id: 'step-capital',
      kind: 'single-choice',
      title: 'Quel capital pouvez-vous mobiliser dès maintenant ?',
      variable: 'capital',
      options: [
        { label: 'Moins de 10 000 €', value: 'moins_10k', next: 'step-formation-reason' },
        { label: '10 000 € - 20 000 €', value: '10k_20k', next: 'step-formation-reason' },
        { label: '20 000 € - 50 000 €', value: '20k_50k', next: 'step-formation-reason' },
        { label: '50 000 € - 100 000 €', value: '50k_100k', next: 'step-besoin-principal' },
        { label: 'Plus de 100 000 €', value: 'plus_100k', next: 'step-besoin-principal' },
      ],
    },
    {
      id: 'step-besoin-principal',
      kind: 'single-choice',
      title: 'Qu’est-ce qui vous aiderait le plus aujourd’hui ?',
      variable: 'primary_need',
      options: [
        { label: 'Accéder à un flux constant d’opportunités off-market', value: 'flux_opportunites', next: 'step-mid-besoin' },
        { label: 'Trouver des investisseurs / partenaires', value: 'investisseurs', next: 'optin-standard' },
        { label: 'Déléguer la prospection / sourcing', value: 'deleguer_prospection', next: 'step-mid-besoin' },
      ],
    },
    {
      id: 'step-mid-besoin',
      kind: 'single-choice',
      title: 'Quelle est votre plus grande difficulté aujourd’hui ?',
      variable: 'mid_need',
      options: [
        { label: 'Trouver des opportunités', value: 'trouver_opportunites', next: 'step-high-besoin' },
        { label: 'Financer mes opérations', value: 'financer_operations', next: 'step-high-besoin' },
        { label: 'Trouver des partenaires', value: 'trouver_partenaires', next: 'step-high-besoin' },
      ],
    },
    {
      id: 'step-high-besoin',
      kind: 'single-choice',
      title: 'Qu’est-ce qui vous aiderait le plus aujourd’hui ?',
      variable: 'high_need',
      options: [
        { label: 'Accéder à un flux constant d’opportunités off-market', value: 'flux_opportunites', next: 'step-high-capital' },
        { label: 'Trouver des partenaires / investisseurs', value: 'investisseurs', next: 'step-high-capital' },
        { label: 'Déléguer la prospection / sourcing', value: 'deleguer_prospection', next: 'step-high-capital' },
      ],
    },
    {
      id: 'step-high-capital',
      kind: 'single-choice',
      title: 'Quel capital pouvez-vous activer dès maintenant ?',
      variable: 'high_capital',
      options: [
        { label: 'Moins de 50 000 €', value: 'moins_50k', next: 'optin-incubator' },
        { label: 'Plus de 50 000 €', value: 'plus_50k', next: 'optin-incubator' },
      ],
    },
    {
      id: 'step-formation-reason',
      kind: 'single-choice',
      title: 'Pourquoi souhaitez-vous devenir Marchand de Biens ?',
      variable: 'formation_reason',
      options: [
        { label: 'Rejoindre un réseau de professionnels', value: 'reseau', next: 'step-cpf' },
        { label: 'Devenir indépendant', value: 'independant', next: 'step-cpf' },
        { label: 'Changer de vie', value: 'changer_vie', next: 'step-cpf' },
      ],
    },
    {
      id: 'step-cpf',
      kind: 'single-choice',
      title: 'Avez-vous du CPF disponible ?',
      subtitle: 'C’est souvent ce qui fait la différence entre “je veux” et “je démarre”.',
      variable: 'cpf_status',
      options: [
        { label: 'Oui', value: 'oui', next: 'optin-formation' },
        { label: 'Non', value: 'non', next: 'optin-formation' },
        { label: 'Je ne sais pas', value: 'ne_sais_pas', next: 'optin-formation' },
      ],
    },
    {
      id: 'optin-formation',
      kind: 'contact',
      title: 'Recevez le plan complet du Marchand de Biens',
      subtitle: 'Un guide 100 % concret pour comprendre le fonctionnement, la fiscalité et les étapes clés d’une première opération.',
      variable: 'formation_contact',
      optinType: 'formation',
      submitLabel: 'Recevoir le plan immédiatement',
      successRedirect: '/funnels/typ/axio',
      fields: [
        { name: 'firstName', label: 'Prénom', placeholder: 'Jean', required: true, autoComplete: 'given-name' },
        { name: 'postalCode', label: 'Code postal', placeholder: '75008', required: true, autoComplete: 'postal-code' },
        { name: 'phone', label: 'Téléphone', type: 'tel', placeholder: '06 12 34 56 78', required: true, autoComplete: 'tel' },
        { name: 'email', label: 'Email', type: 'email', placeholder: 'jean.dupont@email.fr', required: true, autoComplete: 'email' },
      ],
    },
    {
      id: 'optin-standard',
      kind: 'contact',
      title: 'Veuillez entrer vos informations pour obtenir votre plan d’action',
      subtitle: 'Le plan clair et concret pour comprendre comment les MDB structurent, financent et revendent leurs opérations.',
      variable: 'standard_contact',
      optinType: 'standard',
      submitLabel: 'Voir le résultat',
      successRedirect: '/funnels/typ/greenbull',
      fields: [
        { name: 'firstName', label: 'Prénom', placeholder: 'Jean', required: true, autoComplete: 'given-name' },
        { name: 'postalCode', label: 'Code postal', placeholder: '75008', required: true, autoComplete: 'postal-code' },
        { name: 'phone', label: 'Téléphone', type: 'tel', placeholder: '06 12 34 56 78', required: true, autoComplete: 'tel' },
        { name: 'email', label: 'Email', type: 'email', placeholder: 'jean.dupont@email.fr', required: true, autoComplete: 'email' },
      ],
    },
    {
      id: 'optin-incubator',
      kind: 'contact',
      title: 'Recevez les dernières analyses du marché',
      subtitle: 'Et obtenez une mise en relation avec un réseau de Marchands de Biens.',
      variable: 'incubator_contact',
      optinType: 'incubateur',
      submitLabel: 'Valider mon profil',
      successRedirect: '/funnels/typ/greenbull',
      fields: [
        { name: 'firstName', label: 'Prénom', placeholder: 'Jean', required: true, autoComplete: 'given-name' },
        { name: 'postalCode', label: 'Code postal', placeholder: '75008', required: true, autoComplete: 'postal-code' },
        { name: 'phone', label: 'Téléphone', type: 'tel', placeholder: '06 12 34 56 78', required: true, autoComplete: 'tel' },
        { name: 'email', label: 'Email', type: 'email', placeholder: 'jean.dupont@email.fr', required: true, autoComplete: 'email' },
      ],
    },
  ],
};

